[package]
name = "tweaker"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.11.0-alpha.1" }
anyhow = "1.0.82"
libadwaita = "0.9.0-alpha.0"

[build-dependencies]
glib-build-tools = "0.18.0"
